<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.22" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.15.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bytescout.Pdf.DAL\Bytescout.Pdf.DAL.csproj" />
  </ItemGroup>


</Project>
